name: Always Fail Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  fail-job:
    runs-on: ubuntu-latest
    steps:
      - name: This step will always fail
        run: |
          echo "This workflow is designed to fail"
          exit 1  # This command forces the step to fail
      
      - name: This step will never run
        run: |
          echo "You won't see this because the previous step failed" 